# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9a45aa263b2b18b0c702a3dd447c48abb951bf3e49deab446d2bcce2b2a44ff790c026f336bf07ec83fafd70ecd75e08e20f762242659e9947cce702321ab18

test:
  secret_key_base: a3aca98f671801427b553048686fc322ecdc538cef07fc0fce3c2b6b11070fc92d43a35e66d9222aea3f7edbf9545d923de96126f2fe335307312137f2aec478

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
